DROP TABLE IF EXISTS rbac_context_type CASCADE;
-- ;;
DROP TABLE IF EXISTS rbac_context CASCADE;
-- ;;
DROP TABLE IF EXISTS rbac_role CASCADE;
-- ;;
DROP TABLE IF EXISTS rbac_role_assignment CASCADE;
-- ;;
DROP TABLE IF EXISTS rbac_super_admin CASCADE;
-- ;;
DROP TABLE IF EXISTS rbac_permission CASCADE;
-- ;;
DROP TABLE IF EXISTS rbac_role_permission CASCADE;
-- ;;
